plugins: rubocop-rspec

AllCops:
  NewCops: enable

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MethodLength:
  Enabled: false

RSpec/Metrics/AbcSize:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false  

Style/Documentation:
  Enabled: false
